#!/usr/bin/env python

import cgi, re
#import cgitb
#cgitb.enable()

form = cgi.FieldStorage()

if 'file' in form:
  fileitem = form['file']
  if fileitem.filename:
    fn = re.sub('[^A-Za-z0-9\.]', '_', fileitem.filename)
    open('/home/pi/uploads/' + fn, 'wb').write(fileitem.file.read())


print """\
Content-Type: text/html\n
<html>
<body>
OK
</body>
</html>
"""

