#!/usr/bin/env python

import cgi, os, json
from common import *

requireAuth()

KEEP = ['st_mtime', 'st_size']
def stat2obj(stat):
  return {k: getattr(stat, k) for k in dir(stat) if k in KEEP}

p = getUploadDir()
l = os.listdir(p)
l = map(lambda n: {'name': n, 'stat': stat2obj(os.stat(p + '/' + n))}, l)

print """\
Content-Type: application/json\n
%s
""" % (json.dumps(l))

