name: Build Svelte App

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      uses: Borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd webUI install
    - name: Yarn Build
      uses: Borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd webUI build
      env:
        CI: true
